#!/bin/bash

# this script activates the conda environment containing pymcfost
eval "$(conda shell.bash hook)"
conda activate pyspedas

python /data/jhyl3/windy-dust/mcfost_files/dark_lane.py $1

exit 0