#!/bin/bash

# --- change to directory where pipeline run ---
cd $1

para_path=$(find . -maxdepth 1 -type f -name "*.para")

# --- check for existing _run_param.txt file ---
if [ -f "_run_param.txt" ]; then
    echo 'Using existing run parameters file.'
else
    echo 'Creating new run parameters file.'
    # --- input surface mass loss rate and stalling grain size ---
    echo -e "pwd: $1\nsmlr: $2 $3 $4 \na_stl: $5\nincl: $6" >_run_param.txt
fi

# --- use parameter file to calculate correct grain size resolution
python /data/jhyl3/windy-dust/mcfost_files/gs_resolution.py

# --- generating data disk file. if exists, then replaces ---
mcfost $para_path -disk_struct
if [ -d data_disk_original ]; then rm -r data_disk_original; fi
mv data_disk data_disk_original

# --- check for existing density fits file ---
if [ -f "settled_density.fits" ]; then
    echo 'Density fits file already exists. Exiting.'
    exit 1
else
    echo 'Generating new density fits file.'
fi

python /data/jhyl3/windy-dust/mcfost_files/df_fits_gen.py

# check if density fits file was created
if [ ! -f "settled_density.fits" ]; then
    echo "Density fits file not created. Check for errors."
    exit 1
else
    echo "Density fits file created successfully."
    exit 0
fi