#!/bin/bash

# This script initialises a run's directory

# --- check and cd to intended directory ---
dir_int="$1"
if [ ! -d "$dir_int" ]; then echo "Creating $dir_int..." && mkdir "$dir_int"; else echo "$dir_int already exists"; fi
cd $dir_int
echo "Current directory: $(pwd)"
if [ ! -f "output_view.ipynb" ]; then cp /data/jhyl3/mcfost_files/output_view.ipynb .; fi
if [ ! -f "ref4.1.para" ]; then cp /data/jhyl3/mcfost_files/ref4.1.para .; fi
echo "Copying files..."
exit 0