#!/bin/bash

eval "$(conda shell.bash hook)"
conda activate pyspedas

# suppose the same parameter file is used for all runs, i.e. the parameter
# that is being changed is not in the parameter file (e.g. sigma_dot, a_stl)
# so only _run_param.txt needs to be changed

param_values=( "$@" )

# calculate grain size resolution and update parameter file
python /data/jhyl3/windy-dust/mcfost_files/gs_resolution.py
rm old_para.bak # remove clutter

# preemptively generate PSFs

# j tracks whether psf generation has started
j=0
if [ ! -d "psf_fits" ]; then
    j=1
    python /data/jhyl3/windy-dust/mcfost_files/psf_pregen.py &
    psf_process_id=$!
    echo "PSF PID: $psf_process_id"
else
    echo "psf_fits directory already exists. Skipping PSF generation."
fi

# initialise counter: finds how many param_* directories already exist
i=$(find . -maxdepth 1 -type d -name "param_*" | wc -l)
((i++))
k=$i # counter for image_gen later

for arg in "${param_values[@]}"; do

    echo "$i, $arg" >> param_space.csv
    mkdir "param_$i" && cd "param_$i"
    cp ../ref4.1.para ./
    bash ../../sed_gen 2e-12 10 -1.5 ${arg} NaN &
    cd ..
    ((i++))
    sleep 2

done

if [ $j -eq 1 ]; then
    echo "Waiting for PSF generation to complete..."
    wait $psf_process_id
    echo "PSF generation completed."
fi

wait
echo "All data_th jobs complete."


for arg in "${param_values[@]}"; do
    cd "param_$k"
    bash ../../image_gen 0.8 2.0 4.4 7.7 12.8 21.0 && python ../../dark_lane.py ../psf_fits &
    cd ../
    ((k++))
    sleep 2
done

wait

rm -r ./param_*/data_disk_original ./param_*/settled_density.fits # clean up
