#!/bin/bash

# # --- check and cd to intended directory ---
# dir_int=$1
# if [ ! -d "$dir_int"]; then echo "Creating $dir_int..." && mkdir "$dir_int"; fi
# if [ ! -f "output_view.ipynb" ]; then cp /data/jhyl3/mcfost_files/output_view.ipynb $dir_int; fi
# cd $dir_int
# echo "Current directory: $(pwd)"

# --- check for parameter file(s) and obtain parameter file path ---
para_count=$(ls -1 *.para | wc -l)
if [ $para_count -eq 0 ]; then
    echo "No .para files found in the current directory. Exiting."
    exit 1
elif [ $para_count -gt 1 ]; then
    echo "Multiple .para files found. Please ensure only one is present. Exiting."
    exit 1
else
    echo "Single .para file found."
fi

para_path=$(find . -maxdepth 1 -type f -name "*.para")

# --- generate _run_param.txt file ---
echo 'Creating new run parameters file.'
echo -e "pwd: $(pwd)\nsmlr: $1 $2 $3 \na_stl: $4\nincl: $5" >_run_param.txt

# --- use parameter file to calculate correct grain size resolution ---
# --- and simultaneously generate PSFs ---
python /data/jhyl3/windy-dust/mcfost_files/gs_resolution.py &
process_id=$!
echo "PID: $process_id"
if [ -d "psf_fits" ]; then
    echo "psf_fits directory already exists. Skipping psf generation."
else
    echo "Generating psf_fits directory."
    python /data/jhyl3/windy-dust/mcfost_files/psf_pregen.py &
    psf_process_id=$!
    echo "PSF PID: $psf_process_id"
fi

wait $process_id
echo "Grain size resolution calculation completed."
# sleep 20

# --- check for density fits file ---
if [ -f "settled_density.fits" ]; then
    echo "Density fits file found. Proceeding with mcfost."
else
# fields are: surface mass loss rate (g cm-2 s-1) at reference radius; reference radius; power law index; global minimum stalling grain size; IF inclination (rad)
    echo "Density fits file not found. Generating new density fits file."
    bash /data/jhyl3/windy-dust/mcfost_files/fits_gen $(pwd) $1 $2 $3 $4 $5
    if [ $? -ne 0 ]; then
        echo "Error generating density fits file. Exiting."
        exit 1
    fi
    echo "Proceeding with mcfost."
fi

if [ ! -d "data_disk" ]; then
    echo "Generating data_disk."
    mcfost $para_path -df settled_density.fits -disk_struct &
fi

if [ ! -d "data_th" ]; then
    echo "Generating data_th."
    mcfost $para_path -df settled_density.fits
fi


wait
exit 0

# unused code

# check if cutoff provided; if not, no argument passed
# if [ $3 ]; then
#     echo "Using cutoff value: $3"
#     mcfost $para_path -disk_struct -cutoff $3
# else
#     mcfost $para_path -disk_struct
